# ≡≡≡≡≡≡≡≡≡≡≡≡ Download executable ≡≡≡≡≡≡≡≡≡≡≡≡
FROM --platform=$BUILDPLATFORM boky/tool-downloader AS build
ARG TARGETPLATFORM
ARG BUILDPLATFORM
ARG PROJECT
ARG DOWNLOAD_TEMPLATE
ARG VERIFY_COMMAND
ARG VERSION
ARG NAME
ARG PRE_INSTALL
ARG POST_INSTALL
RUN tool-downloader

# ≡≡≡≡≡≡≡≡≡≡≡≡ Create the image ≡≡≡≡≡≡≡≡≡≡≡≡
FROM --platform=linux/amd64 ubuntu
ARG TARGETPLATFORM
COPY --from=build /usr/local/bin/ipfs /ipfs
WORKDIR /work
ENTRYPOINT [ "/ipfs" ]

FROM --platform=linux/arm64 ubuntu
ARG TARGETPLATFORM
COPY --from=build /usr/local/bin/ipfs /ipfs
WORKDIR /work
ENTRYPOINT [ "/ipfs" ]

FROM --platform=linux/arm/v7 ubuntu
ARG TARGETPLATFORM
COPY --from=build /usr/local/bin/ipfs /ipfs
WORKDIR /work
ENTRYPOINT [ "/ipfs" ]

FROM --platform=linux/386 i386/ubuntu
ARG TARGETPLATFORM
COPY --from=build /usr/local/bin/ipfs /ipfs
WORKDIR /work
ENTRYPOINT [ "/ipfs" ]

